Provide contiguous inputs to `causal_conv1d_fwd`
This addresses the following problem:

```
RuntimeError: causal_conv1d with channel last layout requires strides (x.stride(0) and x.stride(2)) to be multiples of 8
```